services:
  restaurants.presentation.api:
    image: restaurants.presentation.api
    build:
      context: .
      dockerfile: Presentation/Restaurants.Presentation.Api/Dockerfile
    environment:
      - ConnectionStrings__RestaurantsDb=Server=sqlserver-container,1433;Database=RestaurantDb;User Id=sa;Password=restaurantDb123!;Trusted_Connection=False;MultipleActiveResultSets=True;Encrypt=False;
      - BlobStorage__ConnectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=restaurantStore123!;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver-container
      - azure-storage-emulator
    ports:
      - "5001:8080"
    networks:
      - restaurant-network
    restart: unless-stopped

  sqlserver-container:
    platform: linux/amd64

  azure-storage-emulator:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite-data:/data
    environment:
      - AZURITE_ACCOUNTS=devstoreaccount1:restaurantStore123!
    networks:
      - restaurant-network

networks:
  restaurant-network:
    driver: bridge

volumes:
  sqlserver-data:
  azurite-data:
